name: plassusuario
description: Plass nace para conectar afiliados y usuarios que tienen necesidad de trasladarse de un lugar a otro pagando tarifas asequibles y con seguridad garantizada. Plass es la app de conectividad más efectiva del país.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 8.0.0+8.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  here_sdk:
    path: plugins/here_sdk

  cupertino_icons: ^1.0.2
  firebase_core: ^1.14.1
  firebase_messaging: ^11.2.13
  get: ^4.6.1
  url_launcher: ^6.0.20
  cloud_firestore: ^3.1.12
  firebase_auth: ^3.3.14
  package_info_plus: ^1.4.2
  skeletons: ^0.0.3
  country_code_picker: ^2.0.2
  device_info_plus: ^3.2.3
  location: ^4.3.0
  pin_code_fields: ^7.4.0
  cached_network_image: ^3.2.0
  intl: ^0.17.0
  badges: ^2.0.2
  image_picker: ^0.8.5
  image_cropper: ^1.5.1
  firebase_storage: ^10.2.12
  bubble: ^1.2.1
  flutter_rating_bar: ^4.0.0
  connectivity_plus: ^2.3.0
  qr_code_scanner: ^0.7.0
  flutter_ringtone_player: ^3.2.0
  enum_to_string: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/PLASS.png
    - assets/main/foreground-icon.png
    - assets/main/PlassLogo.png
    - assets/main/Artwork.png
    - assets/icons/sideMenu.png
    - assets/icons/HandUp.png
    - assets/icons/currentLocation.png
    - assets/icons/pickup.png
    - assets/icons/drop.png
    - assets/icons/cars/standar.png
    - assets/icons/cars/standar-min.png
    - assets/icons/cars/standar-min-ios.png
    - assets/icons/by-woman.png
    - assets/icons/camera.png
    - assets/icons/taxi.png
    - assets/icons/min.png
    - assets/icons/med.png
    - assets/icons/max.png
    - assets/3d/sedan.obj
    - assets/3d/plane.obj